apiVersion: v1
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: gitops-production
      namespace: argocd
    spec:
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"
      destinations:
        - namespace: "production"
          server: "*"
      sourceRepos:
        - "*"
kind: List
