apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  labels:
    name: staging
    flow: gitops
spec:
  project: gitops-staging

  source:
    repoURL: https://github.com/maximeancellin/demo-argocd-renovate.git
    targetRevision: main
    path: cluster/staging

    directory:
      recurse: true
      include: "*.yaml"

  destination:
    name: in-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

  revisionHistoryLimit: 10
